### ISSUE TITLE
Status escalation for (critical) changes

### ISSUE THREAD

**Issue by Drivingralle** [Zodiac1978/tl-template-checker#19]
Not all changes in a parent theme are critical, therefore always saying if there is a diff between the two themes, it's a red status is overkill. 
I think it would be nice to have an important looking status, that shows up if a parent theme changes something very important.

I'm thinking about an extra parameter, that can be added by the author, if there is an important version change that the child-theme needs an update.

Ex.:
@version     0.9.3
@stable       0.9.1

This way the status of all changes can be yellow and if the version number of the child theme is lower then the stable version it shows up in red. 

This way it is possible to give general user/website owner this plugin to check there child theme on there own. If they always get a red error it generates often unnecessary requests for changes to the child theme.
If I remember it right, the base idea was that this plugin should help none technically people to find out if there is a need to work on there child theme.

Let's discuss.

**Comment by glueckpress** [comment]
Who will determine what’s critical, though? A parent theme author will know what a critical template change is in the general context of their theme. But a change seen as _less_ than critical by the author can still be very critical in the context of an individual user’s child theme. 

Giving the authority to categorize changes to the parent theme author could lead to a situation where a child theme user trusting a less-than-critical change would wind up in great trouble, because in their individual context the change in fact _was_ critical.

Instead of categorizing changes, I’d suggest a general user notice education the user about exactly these types of situations and that they’d best test _every_ change made to a template they use in their child theme.

**Comment by Zodiac1978** [comment]
Education is a good point. We will need to add some infos somewhere (just PHP files, functions.php not checked because special case, etc.).

I like the idea of marking an update to a minor change (e.g. you are just adding some spaces for codestyling). But checking every change that was made seems to be the better solution.

Let us put this on hold and wait for more user feedback if this is more used. Maybe we could reconsidering this in the future (as an extra feature).

**Comment by staude** [comment]
Let this and another in Cologne discuss, with more feedback from the participants of Torsten's session.

I would also like to hear what you think, instead of Versionenummern (which hardly use themes) with hash values of the files to work. This would have the advantage that it would work with any theme available.

See you in a week :-)

**Comment by LeisureLarry** [comment]
I really would like the possibility to give a version a status tag like security-update

**Comment by Zodiac1978** [comment]
I think a critical theme update should be mentioned in a theme changelog (or better upgrade notice) which is a missing feature, but I think a global system makes much more sense here.

See:
https://meta.trac.wordpress.org/ticket/215
https://core.trac.wordpress.org/ticket/22810
https://meta.trac.wordpress.org/ticket/45

And after @glueckpress post I think every change (like a class name change) can be dramatic for the child theme, so I think I will close it as wontfix.
